# Generated by Django 5.1 on 2024-08-27 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="cargo_type",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="delivery_city",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="distance",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="pickup_city",
        ),
        migrations.AddField(
            model_name="shipment",
            name="price",
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="volume",
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="weight",
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="city",
            name="longitude",
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cargo_type", models.CharField(max_length=20)),
                (
                    "city_commection",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="logistics.cityconnection",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
