# Generated by Django 5.1 on 2024-08-21 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="client_name",
            new_name="name",
        ),
    ]
