# Generated by Django 3.1.13 on 2024-09-09 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_customer',
            new_name='is_client',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_employee',
            new_name='is_dispatcher',
        ),
    ]
