# Generated by Django 5.1 on 2024-08-28 05:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0002_remove_shipment_cargo_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="cargo_type",
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_location",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_location",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="planned_delivery",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="order",
            name="volume",
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="weight",
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
