# Generated by Django 3.1.13 on 2024-09-09 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_auto_20240909_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='planned_delivery',
            field=models.DateField(default=datetime.date(2024, 9, 9)),
        ),
    ]
