# Generated by Django 5.1 on 2024-08-28 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0003_remove_order_cargo_type_order_delivery_location_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="city_commection",
            new_name="city_connection",
        ),
    ]
