# Generated by Django 5.1 on 2024-08-28 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0004_rename_city_commection_order_city_connection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="city_connection",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="client",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="delivery_location",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="pickup_location",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="planned_delivery",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="volume",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="weight",
        ),
        migrations.AddField(
            model_name="shipment",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="logistics.order",
            ),
            preserve_default=False,
        ),
    ]
