# Generated by Django 5.1 on 2024-08-28 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0005_remove_shipment_city_connection_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shipment",
            old_name="shipment_status",
            new_name="status",
        ),
    ]
