# Generated by Django 5.1 on 2024-08-28 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0006_rename_shipment_status_shipment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="logistics.order"
            ),
        ),
    ]
