# Generated by Django 5.1 on 2024-08-29 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0007_alter_shipment_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_pending",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipment",
                to="logistics.order",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("rejected", "Rejected"),
                ],
                default="in_transit",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="shipmentstatushistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("rejected", "Rejected"),
                ],
                max_length=20,
            ),
        ),
    ]
