# Generated by Django 5.1 on 2024-08-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0008_order_is_pending_alter_shipment_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_pending",
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("rejected", "Rejected")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[("in_transit", "In Transit"), ("delivered", "Delivered")],
                default="in_transit",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="shipmentstatushistory",
            name="status",
            field=models.CharField(
                choices=[("in_transit", "In Transit"), ("delivered", "Delivered")],
                max_length=20,
            ),
        ),
    ]
