# Generated by Django 5.1 on 2024-08-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0009_remove_order_is_pending_order_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                    ("accepted", "Accepted"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
