# Generated by Django 5.1 on 2024-08-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0010_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="vehicle",
        ),
        migrations.AddField(
            model_name="driver",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
