# Generated by Django 5.1 on 2024-08-30 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0011_remove_shipment_vehicle_driver_is_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="vehicle",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="logistics.vehicle",
            ),
            preserve_default=False,
        ),
    ]
